

-- Database: restapi-exercise

-- DROP DATABASE IF EXISTS "restapi-exercise";

CREATE DATABASE "restapi-exercise"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Japanese_Japan.932'
    LC_CTYPE = 'Japanese_Japan.932'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
-- Table: public.product_category

-- DROP TABLE IF EXISTS public.product_category;

CREATE TABLE IF NOT EXISTS public.product_category
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT product_category_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_category_uuid UNIQUE (category_uuid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product_category
    OWNER to postgres;

-- Table: public.product

-- DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(30) COLLATE pg_catalog."default",
    price integer,
    category_id integer,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_uuid UNIQUE (product_uuid),
    CONSTRAINT fk_product__category FOREIGN KEY (category_id)
        REFERENCES public.product_category (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product
    OWNER to postgres;
-- Index: idx_product__category_id

-- DROP INDEX IF EXISTS public.idx_product__category_id;

CREATE INDEX IF NOT EXISTS idx_product__category_id
    ON public.product USING btree
    (category_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public.product_stock

-- DROP TABLE IF EXISTS public.product_stock;

CREATE TABLE IF NOT EXISTS public.product_stock
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    stock_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    stock integer,
    product_id integer,
    CONSTRAINT product_stock_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_stock_uuid UNIQUE (stock_uuid),
    CONSTRAINT fk_product_stock__product FOREIGN KEY (product_id)
        REFERENCES public.product (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product_stock
    OWNER to postgres;
-- Index: idx_product_stock__product_id

-- DROP INDEX IF EXISTS public.idx_product_stock__product_id;

CREATE INDEX IF NOT EXISTS idx_product_stock__product_id
    ON public.product_stock USING btree
    (product_id ASC NULLS LAST)
    TABLESPACE pg_default;